version: "3"

services:
    web:
        container_name: tybaapp
        restart: always
        build: .
        ports:
            - "5000:3000"
        links:
            - mysql
        
    mysql:
        container_name: mysqldatabase   
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
          MYSQL_DATABASE: 'tybadb'
          MYSQL_ROOT_PASSWORD: 'root'   
        ports:   
            - "3306:3306"